color: null
fieldLayouts:
  94e82503-af6e-45b7-9dea-51feced06aff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:04:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cdf57a8b-8aaf-48e2-b7fd-969efa7f94b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:06:31+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1414f508-5783-43aa-bca5-fbb039e282d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:12:32+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31798797-d79c-4137-941c-6d0022fe07ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d6a5523-7d80-4242-bfe0-70a8b149fdc9
        userCondition: null
handle: categories
hasTitleField: true
icon: ''
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
