altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9d242fec-bb84-4fbd-af83-dc21b6ff6461:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-18T15:21:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: efad2db2-42a1-4e9d-8a0c-28746a546bd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 542b44e2-975d-4c45-be8d-0377f9cc5019
        userCondition: null
fs: local
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
