columnSuffix: null
handle: category
instructions: null
name: Category
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:205a9a00-d12c-4eb2-9d7a-728a4fba7d97' # Categories
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
