defaultPlacement: end
enableVersioning: true
entryTypes:
  - 19178fcc-602e-4e2e-a2a4-abf44f2ec6a3 # House
handle: house
maxAuthors: 1
name: House
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: house/_entry.twig
    uriFormat: 'house/{slug}'
type: channel
